sudo: required
services:
  -docker

before_install:
  - docker build -t amitv08/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true amitv08/react-test npm test
  
after_success:
  - docker build -t amitv08/multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t amitv08/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t amitv08/multi-server -f ./server/Dockerfile.dev ./server
  - docker build -t amitv08/multi-worker -f ./worker/Dockerfile.dev ./worker
# Login to docker hub using CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin    
# Push images to Docker Hub
  - docker push amitv08/multi-client
  - docker push amitv08/multi-nginx
  - docker push amitv08/multi-server
  - docker push amitv08/multi-worker
  